# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/stack.optimism-stacks.net_cliquel1s.yaml
- bases/stack.optimism-stacks.net_deployers.yaml
- bases/stack.optimism-stacks.net_datatransportlayers.yaml
- bases/stack.optimism-stacks.net_sequencers.yaml
- bases/stack.optimism-stacks.net_batchsubmitters.yaml
- bases/stack.optimism-stacks.net_gasoracles.yaml
- bases/stack.optimism-stacks.net_actors.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_cliquel1s.yaml
#- patches/webhook_in_deployers.yaml
#- patches/webhook_in_datatransportlayers.yaml
#- patches/webhook_in_sequencers.yaml
#- patches/webhook_in_batchsubmitters.yaml
#- patches/webhook_in_gasoracles.yaml
#- patches/webhook_in_actors.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_cliquel1s.yaml
#- patches/cainjection_in_deployers.yaml
#- patches/cainjection_in_datatransportlayers.yaml
#- patches/cainjection_in_sequencers.yaml
#- patches/cainjection_in_batchsubmitters.yaml
#- patches/cainjection_in_gasoracles.yaml
#- patches/cainjection_in_actors.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
