# permissions for end users to view datatransportlayers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datatransportlayer-viewer-role
rules:
- apiGroups:
  - stack.optimism-stacks.net
  resources:
  - datatransportlayers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stack.optimism-stacks.net
  resources:
  - datatransportlayers/status
  verbs:
  - get
