# permissions for end users to view deployers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployer-viewer-role
rules:
- apiGroups:
  - stack.optimism-stacks.net
  resources:
  - deployers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stack.optimism-stacks.net
  resources:
  - deployers/status
  verbs:
  - get
