# permissions for end users to edit deployers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployer-editor-role
rules:
- apiGroups:
  - stack.optimism-stacks.net
  resources:
  - deployers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.optimism-stacks.net
  resources:
  - deployers/status
  verbs:
  - get
