
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.optimism-stacks.net
  resources:
  - cliquel1s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.optimism-stacks.net
  resources:
  - cliquel1s/finalizers
  verbs:
  - update
- apiGroups:
  - stack.optimism-stacks.net
  resources:
  - cliquel1s/status
  verbs:
  - get
  - patch
  - update
