# permissions for end users to view sequencers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sequencer-viewer-role
rules:
- apiGroups:
  - stack.optimism-stacks.net
  resources:
  - sequencers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stack.optimism-stacks.net
  resources:
  - sequencers/status
  verbs:
  - get
