# permissions for end users to edit sequencers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sequencer-editor-role
rules:
- apiGroups:
  - stack.optimism-stacks.net
  resources:
  - sequencers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.optimism-stacks.net
  resources:
  - sequencers/status
  verbs:
  - get
